name: Periodic Nix Flake Update
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    # Daily at midnight (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix --extra-experimental-features "nix-command flakes pipe-operators" flake update
      - uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: GitHub Actions (Updater)
          author_email: actions@github.com
          commit: 'Update flake (automatic)'
          pull: '--rebase --autostash ...'
          push: true
