name: Periodic Nix Flake Update
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    # Daily at midnight (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: nix flake update
      - run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add flake.lock
          git commit -m "Update flake.lock"
          git push origin main
